[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mfmodeling"
version = "1.0.3"
description = "Multi-fidelity modeling using Gaussian process regression"
authors = [
    { name = "Shinya Maeyama", email = "maeyama.shinya@nifs.ac.jp" }
]
readme = "README.md"
license = {text = "MIT License"}
requires-python = ">=3.7"

dependencies = [
    "numpy>=2.0",
    "torch>=2.1",
    "gpytorch>=1.11",
]

[project.optional-dependencies]
examples = [
    "matplotlib>=3.7",
    "pandas>=2.0",
    "scikit-learn>=1.2",
]

[tool.setuptools]
packages = ["mfmodeling"]
package-dir = {"" = "src"}

